### ISSUE TITLE
Navigate to Great Wall return: Exception caught by image resource service

### ISSUE THREAD

**Issue by DiegoGW** [gskinnerTeam/flutter-wonderous-app#117]
**Steps to reproduce**
1. Get latest version of wonderous app (This is the log when this issue was created - commit a38f5644117eba8b5f2093cce26ac66ab8ce1f65 (HEAD -> main, origin/main, origin/HEAD)
Author: Shawn <shawn@gskinner.com>
Date:   Thu Sep 7 10:24:01 2023 -0600

    Initialize google maps sdk for web platform)

2. flutter run (target: Pixel 6 / Android 13 + samsung A03 / Android 11 + iPhone 14Pro / iOS 17)
3. Navigate to the Great Wall (Navigate to: /wonder/greatWall?t=0)
4. Check error logs

**Expected results**
None exceptions should be returned

**Actual results**
This exception is logged after navigating to the Great Wall:
```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 400,
https://proxy.wonderous.app:8081/https://images.metmuseum.org/CRDImages/as/original/DP153769.jpg

When the exception was thrown, this was the stack:
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:117:9)
<asynchronous suspension>
#1      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:973:3)
<asynchronous suspension>

Image provider:
  NetworkImage("https://proxy.wonderous.app:8081/https://images.metmuseum.org/CRDImages/as/original/DP153769.jpg",
  scale: 1.0)
Image key:
  NetworkImage("https://proxy.wonderous.app:8081/https://images.metmuseum.org/CRDImages/as/original/DP153769.jpg",
  scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Screenshots or Video**
[Check this video](https://drive.google.com/file/d/1_GhcSHpHu_ow_t60zXIA_VV2THlLc6OX/view?usp=sharing)

**Flutter Doctor output**
[✓] Flutter (Channel master, 3.14.0-14.0.pre.208, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.14.0-14.0.pre.208 on channel master at /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision de25def778 (3 hours ago), 2023-09-10 13:25:28 -0400
    • Engine revision 59b08263f7
    • Dart version 3.2.0 (build 3.2.0-134.0.dev)
    • DevTools version 2.27.0

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/diegogawenda/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/diegogawenda/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/diegogawenda/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Somnio’s iPhone (mobile) • 00008120-001168D83C87C01E • ios            • iOS 16.6.1 20G81
    • macOS (desktop)          • macos                     • darwin-arm64   • macOS 13.5 22G74 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript • Google Chrome 116.0.5845.179

[✓] Network resources
    • All expected network resources are available.

**Comment by DiegoGW** [comment]
This issue is still replicable with the following flutter version:
```
[✓] Flutter (Channel master, 3.14.0-14.0.pre.332, on macOS 13.5 22G74
    darwin-arm64, locale en-US)
    • Flutter version 3.14.0-14.0.pre.332 on channel master at
      /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1b18b1327a (9 hours ago), 2023-09-17 04:07:02 -0400
    • Engine revision 57a4ff3c7f
    • Dart version 3.2.0 (build 3.2.0-171.0.dev)
    • DevTools version 2.28.0-dev.8
```

The error log changed a bit:
```
======== Exception caught by image resource service ================================================
The following SocketException was thrown resolving an image codec:
Connection refused (OS Error: Connection refused, errno = 111), address = proxy.wonderous.app, port = 39196

When the exception was thrown, this was the stack: 
#0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:721:35)
#1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1914:26)
#2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
#3      RawSecureSocket.startConnect (dart:io/secure_socket.dart:299:22)
#4      SecureSocket.startConnect (dart:io/secure_socket.dart:77:28)
#5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2483:26)
#6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2926:12)
#7      _HttpClient._getConnection (dart:_http/http_impl.dart:2931:12)
#8      _HttpClient._openUrl (dart:_http/http_impl.dart:2786:12)
#9      _HttpClient.getUrl (dart:_http/http_impl.dart:2628:48)
#10     NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:106:59)
#11     NetworkImage.loadImage (package:flutter/src/painting/_network_image_io.dart:68:14)
#12     ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:521:39)
#13     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:380:22)
#14     ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:518:81)
#15     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:366:9)
#16     ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:480:24)
#17     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:43:39)
#18     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:477:9)
#19     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:363:5)
#20     new CollectibleItem (package:wonders/ui/common/collectible_item.dart:12:20)
#21     HiddenCollectible.build (package:wonders/ui/common/hidden_collectible.dart:22:12)
#22     StatelessElement.build (package:flutter/src/widgets/framework.dart:5544:49)
#23     _GetItElement.build (package:get_it_mixin/src/elements.dart:16:18)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5474:15)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:5190:7)
#26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5456:5)
#27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5450:5)
#28     _GetItElement.mount (package:get_it_mixin/src/elements.dart:9:11)
...     Normal element mounting (7 frames)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4329:16)
#36     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6784:36)
#37     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6796:32)
...     Normal element mounting (47 frames)
#84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4329:16)
#85     Element.updateChild (package:flutter/src/widgets/framework.dart:3840:18)
#86     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:858:37)
#87     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:843:20)
#88     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2838:19)
#89     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:835:12)
#90     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:351:23)
#91     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2659:59)
#92     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1073:15)
#93     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2659:14)
#94     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:340:5)
#95     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:426:5)
#96     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:79:12)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#98     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139:12)
#99     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:361:11)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#101    RenderProxySliver.performLayout (package:flutter/src/rendering/proxy_sliver.dart:54:12)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#103    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:534:13)
#104    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1512:12)
#105    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1421:20)
#106    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#107    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#108    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#109    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#110    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#112    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#113    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#114    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#115    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#116    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#118    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#119    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#120    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#121    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#122    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#123    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#124    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#125    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#126    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#127    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#128    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#129    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#130    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:571:11)
#131    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#132    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#133    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#134    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#135    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#136    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#137    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#138    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#139    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#140    RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:571:11)
#141    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#142    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#143    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#144    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#145    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#146    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#147    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#148    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#149    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#150    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#151    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#152    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#153    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#154    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#155    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#156    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#157    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#158    RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:279:14)
#159    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#160    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#161    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:238:12)
#162    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#163    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#164    RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:438:14)
#165    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#166    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#167    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#168    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:585:43)
#169    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:612:12)
#170    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#171    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#172    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#173    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#174    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#175    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:315:14)
#176    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#177    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#178    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#179    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#180    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#181    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#182    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#183    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#184    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#185    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:585:43)
#186    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:612:12)
#187    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#188    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#189    ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52:11)
#190    RenderStack._computeSize (package:flutter/src/rendering/stack.dart:585:43)
#191    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:612:12)
#192    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#193    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#194    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#195    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#196    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#197    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:173:12)
#198    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:1062:7)
#199    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:237:7)
#200    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:405:14)
#201    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#202    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#203    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#204    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#205    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#206    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#207    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1444:11)
#208    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#209    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#210    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#211    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#212    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#213    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#214    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#215    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#216    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#217    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#218    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#219    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#220    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#221    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#222    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#223    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#224    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#225    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#226    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#227    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#228    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3739:14)
#229    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#230    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#231    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:21)
#232    RenderObject.layout (package:flutter/src/rendering/object.dart:2548:7)
#233    RenderBox.layout (package:flutter/src/rendering/box.dart:2391:11)
#234    _RenderTheaterMixin.performLayout (package:flutter/src/widgets/overlay.dart:884:15)
#235    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2387:7)
#236    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1027:18)
#237    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1040:15)
#238    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:591:23)
#239    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:986:13)
#240    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#241    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#242    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#243    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#244    _invoke (dart:ui/hooks.dart:313:13)
#245    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:354:5)
#246    _drawFrame (dart:ui/hooks.dart:283:31)
Image provider: NetworkImage("https://proxy.wonderous.app:8081/https://images.metmuseum.org/CRDImages/as/original/DP153769.jpg", scale: 1.0)
Image key: NetworkImage("https://proxy.wonderous.app:8081/https://images.metmuseum.org/CRDImages/as/original/DP153769.jpg", scale: 1.0)
====================================================================================================
```

**Comment by DiegoGW** [comment]
This issue is still replicable with:
```
[✓] Flutter (Channel master, 3.14.0-14.0.pre.358, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.14.0-14.0.pre.358 on channel master at /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8936504163 (9 hours ago), 2023-09-19 02:10:24 -0400
    • Engine revision 589bde9a95
    • Dart version 3.2.0 (build 3.2.0-174.0.dev)
    • DevTools version 2.28.0-dev.8
```

**Comment by DiegoGW** [comment]
This issue is still replicable:
```
Flutter (Channel master, 3.15.0-6.0.pre.41, on macOS 13.5 22G74
    darwin-arm64, locale en-US)
    • Flutter version 3.15.0-6.0.pre.41 on channel master at
      /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 76a938bfa6 (84 minutes ago), 2023-09-22 11:23:14 -0700
    • Engine revision ef9ceed1af
    • Dart version 3.2.0 (build 3.2.0-190.0.dev)
    • DevTools version 2.28.0-dev.12
```

**Comment by DiegoGW** [comment]
This issue is still replicable:
 Flutter (Channel master, 3.16.0-2.0.pre.8, on macOS 13.5 22G74 darwin-arm64, locale en-US)
    • Flutter version 3.16.0-2.0.pre.8 on channel master at /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b71f8ce7ae (2 hours ago), 2023-10-02 15:09:38 -0400
    • Engine revision f3a92cb0c4
    • Dart version 3.2.0 (build 3.2.0-221.0.dev)
    • DevTools version 2.28.1

**Comment by esDotDev** [comment]
This should be fixed now, please confirm!

**Comment by DiegoGW** [comment]
Validated in Wonderous latest commit:
commit https://github.com/gskinnerTeam/flutter-wonderous-app/commit/8ac60d46a8bed6c54bcf2df44cccce90a182882f (HEAD -> main, origin/main, origin/HEAD)
Author: Shawn [shawn@gskinner.com](mailto:shawn@gskinner.com)
Date: Thu Oct 5 09:13:02 2023 -0600

Re-ran native_splash generator

**Comment by DiegoGW** [comment]
Validated this doesn't happen anymore in Wonderous with latest commit:
commit https://github.com/gskinnerTeam/flutter-wonderous-app/commit/8ac60d46a8bed6c54bcf2df44cccce90a182882f (HEAD -> main, origin/main, origin/HEAD)
Author: Shawn [shawn@gskinner.com](mailto:shawn@gskinner.com)
Date: Thu Oct 5 09:13:02 2023 -0600

Re-ran native_splash generator
