### ISSUE TITLE
Unhandled Exception: Bad state: Stream has been disposed.

### ISSUE THREAD

**Issue by DiegoGW** [gskinnerTeam/flutter-wonderous-app#121]
**Steps to reproduce**

1. Get latest version of wonderous app (This is the log when this issue was created - commit 8a29d6709668980340b1b59c3d3588f123edd4d8 (HEAD -> main, origin/main, origin/HEAD)

Merge: a38f564 6523ec3
Author: Shawn <shawn@gskinner.com>
Date:   Mon Sep 11 10:01:33 2023 -0600

    Merge pull request #115 from jonahwilliams/combine_advanced_blends
    
    Reduce SaveLayer count of advanced blends.)

2. flutter run (target: iPhone 14 Pro / iOS 16.6.1)
3. Navigate to the Great Wall (Navigate to: /wonder/greatWall?t=0)
4. Go to timeline
5. Scroll to bottom
6. Add the image to your collection
7. View collection
8. Check error log:
```
2023-09-17 16:58:55.186230-0300 Runner[549:35925] [VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Stream has been disposed.
An ImageStream is considered disposed once at least one listener has been added and subsequently all listeners have been removed and no handles are outstanding from the keepAlive method.
To resolve this error, maintain at least one listener on the stream, or create an ImageStreamCompleterHandle from the keepAlive method, or create a new stream for the image.
#0      ImageStreamCompleter._checkDisposed (package:flutter/src/painting/image_stream.dart:667:7)
#1      ImageStreamCompleter.removeListener (package:flutter/src/painting/image_stream.dart:634:5)
#2      MultiFrameImageStreamCompleter.removeListener (package:flutter/src/painting/image_stream.dart:1079:11)
#3      RetryImage.loadImage.<anonymous closure> (package:wonders/logic/common/retry_image.dart:82:23)
#4      ImageStreamCompleter.removeListener (package:flutter/src/painting/image_stream.dart:644:17)
#5      _PendingImage.removeListener (package:flutter/src/painting/image_cache.dart:664:15)
#6      ImageCache.evict (package:flutter/src/painting/image_cache.dart:257:20)
#7      ResizeImage._configureErrorListener.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:1354:45)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Expected results**
None exceptions should be returned

**Actual results**
The unhandled exception described above is logged after adding the great wall timeline element to your collection of objects

**Screenshots or Video**
<img width="1337" alt="Screenshot 2023-09-17 at 5 07 58 PM" src="https://github.com/gskinnerTeam/flutter-wonderous-app/assets/11681325/e7cca5c1-0cd6-46d3-bcdf-23c5aaad44a8">
https://drive.google.com/file/d/10i46YXNsua2Tqmz-UXPMqooJs7Ib6tpw/view?usp=sharing

**Flutter Doctor output**
[✓] Flutter (Channel master, 3.14.0-14.0.pre.332, on macOS 13.5 22G74
    darwin-arm64, locale en-US)
    • Flutter version 3.14.0-14.0.pre.332 on channel master at
      /Users/diegogawenda/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1b18b1327a (9 hours ago), 2023-09-17 04:07:02 -0400
    • Engine revision 57a4ff3c7f
    • Dart version 3.2.0 (build 3.2.0-171.0.dev)
    • DevTools version 2.28.0-dev.8

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/diegogawenda/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/diegogawenda/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/diegogawenda/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.72.0

[✓] Connected device (3 available)
    • Somnio’s iPhone (mobile) • 00008120-001168D83C87C01E • ios            •
      iOS 16.6.1 20G81
    • macOS (desktop)          • macos                     • darwin-arm64   •
      macOS 13.5 22G74 darwin-arm64
    • Chrome (web)             • chrome                    • web-javascript •
      Google Chrome 117.0.5938.88

[✓] Network resources
    • All expected network resources are available.

**Comment by DiegoGW** [comment]
Validated in Wonderous that with latest commit this doesn't happen anymore:
commit https://github.com/gskinnerTeam/flutter-wonderous-app/commit/8ac60d46a8bed6c54bcf2df44cccce90a182882f (HEAD -> main, origin/main, origin/HEAD)
Author: Shawn [shawn@gskinner.com](mailto:shawn@gskinner.com)
Date: Thu Oct 5 09:13:02 2023 -0600

Re-ran native_splash generator

**Comment by DiegoGW** [comment]
Validated in Wonderous that with latest commit this doesn't happen anymore:
commit https://github.com/gskinnerTeam/flutter-wonderous-app/commit/8ac60d46a8bed6c54bcf2df44cccce90a182882f (HEAD -> main, origin/main, origin/HEAD)
Author: Shawn [shawn@gskinner.com](mailto:shawn@gskinner.com)
Date: Thu Oct 5 09:13:02 2023 -0600

Re-ran native_splash generator
