### ISSUE TITLE
Exception caught by widgets library

### ISSUE THREAD

**Issue by DiegoGW** [gskinnerTeam/flutter-wonderous-app#122]
**Steps to reproduce**

1. Get latest version of wonderous app (This is the log when this issue was created - commit https://github.com/gskinnerTeam/flutter-wonderous-app/commit/8a29d6709668980340b1b59c3d3588f123edd4d8 (HEAD -> main, origin/main, origin/HEAD)

Merge: https://github.com/gskinnerTeam/flutter-wonderous-app/commit/a38f5644117eba8b5f2093cce26ac66ab8ce1f65 https://github.com/gskinnerTeam/flutter-wonderous-app/commit/6523ec320b57b97f64f9cd96b098bd11235827be
Author: Shawn [shawn@gskinner.com](mailto:shawn@gskinner.com)
Date: Mon Sep 11 10:01:33 2023 -0600

Merge pull request #115 from jonahwilliams/combine_advanced_blends

Reduce SaveLayer count of advanced blends.)

2. flutter run (target: samsung A03 / Android 11)
3. Navigate to the Great Wall (Navigate to: /wonder/greatWall?t=0)
4. Scroll to bottom
5. Add the element at the bottom to your collection
6. Go to the images and navigate through some of them
7. Go to timeline
8. Keep adding objects to your collection
9. At some point the following error is returned:

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#272f2](state: OverlayState#dd372(entries: [OverlayEntry#b7388(opaque: true; maintainState: false), OverlayEntry#765d8(opaque: false; maintainState: true), OverlayEntry#aa0a0(opaque: true; maintainState: false), OverlayEntry#f3f16(opaque: false; maintainState: true)])):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 2109 pos 12: '_elements.contains(element)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

The relevant error-causing widget was: 
  ScrollConfiguration ScrollConfiguration:file:///Users/diegogawenda/development/wonderous/flutter-wonderous-app/lib/ui/app_scaffold.dart:27:18
When the exception was thrown, this was the stack: 
#2      _InactiveElements.remove (package:flutter/src/widgets/framework.dart:2109:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:4260:30)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4301:35)
#5      MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6784:36)
#6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6796:32)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4329:16)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3834:20)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5499:16)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5637:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5190:7)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2898:19)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#18     _invoke (dart:ui/hooks.dart:313:13)
#19     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:354:5)
#20     _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```

**Expected results**
None exceptions should be returned

**Actual results**
The unhandled exception described above is logged after adding the great wall timeline element (or other) to your collection of objects

**Screenshots or Video**
![Error screen with collection images](https://github.com/gskinnerTeam/flutter-wonderous-app/assets/11681325/9f183058-ff1e-4b43-8171-4248cfeee76b)

**Flutter Doctor output**
```
[✓] Flutter (Channel master, 3.14.0-14.0.pre.332, on macOS 13.5 22G74
darwin-arm64, locale en-US)
• Flutter version 3.14.0-14.0.pre.332 on channel master at
/Users/diegogawenda/fvm/versions/master
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision 1b18b1327a (9 hours ago), 2023-09-17 04:07:02 -0400
• Engine revision 57a4ff3c7f
• Dart version 3.2.0 (build 3.2.0-171.0.dev)
• DevTools version 2.28.0-dev.8

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
• Android SDK at /Users/diegogawenda/Library/Android/sdk
• Platform android-34, build-tools 34.0.0
• ANDROID_HOME = /Users/diegogawenda/Library/Android/sdk
• ANDROID_SDK_ROOT = /Users/diegogawenda/Library/Android/sdk
• Java binary at: /Applications/Android
Studio.app/Contents/jbr/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
17.0.6+0-17.0.6b802.4-9586694)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Build 14E300c
• CocoaPods version 1.12.1

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build
17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.80.2)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.72.0

[✓] Connected device (3 available)
• Somnio’s iPhone (mobile) • 00008120-001168D83C87C01E • ios •
iOS 16.6.1 20G81
• macOS (desktop) • macos • darwin-arm64 •
macOS 13.5 22G74 darwin-arm64
• Chrome (web) • chrome • web-javascript •
Google Chrome 117.0.5938.88

[✓] Network resources
• All expected network resources are available.
```

**Comment by esDotDev** [comment]
Ran through several wonders collecting all artifacts and was unable to reproduce this. Can you verify it's still occuring with the latest version?

**Comment by DiegoGW** [comment]
This was fixed with latest version of Wonderous app:
```
commit 8ac60d46a8bed6c54bcf2df44cccce90a182882f (HEAD -> main, origin/main, origin/HEAD)
Author: Shawn <shawn@gskinner.com>
Date:   Thu Oct 5 09:13:02 2023 -0600

    Re-ran native_splash generator
```

It cannot be replicated anymore.
